version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: fastchat-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
      - DEBUG=${DEBUG:-false}
      - SECRET_KEY=${SECRET_KEY}
      - ONLINE_THRESHOLD_SECONDS=${ONLINE_THRESHOLD_SECONDS:-30}
      - REAPER_INTERVAL_SECONDS=${REAPER_INTERVAL_SECONDS:-60}
      - WS_PING_INTERVAL=${WS_PING_INTERVAL:-15}
      - WS_MAX_MESSAGE_LENGTH=${WS_MAX_MESSAGE_LENGTH:-1000}
    env_file:
      - ../.env
    volumes:
      - ../backend:/app
    networks:
      - fastchat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: fastchat-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000/ws
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - fastchat-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  fastchat-network:
    driver: bridge
    name: fastchat-network
