"""add_user_id_to_users_online

Revision ID: 46e05cc0b5c9
Revises: 965848b780ef
Create Date: 2025-08-20 18:05:58.697667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e05cc0b5c9'
down_revision = '965848b780ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_online', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'users_online', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_online', type_='unique')
    op.drop_column('users_online', 'user_id')
    # ### end Alembic commands ###
