"""Add users_online table

Revision ID: 965848b780ef
Revises: 
Create Date: 2025-08-19 23:43:11.789190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965848b780ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_online',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_online')
    # ### end Alembic commands ###
